server:
  port: 1234
spring:
  profiles:
    include: oauth2, jwt
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
    url: jdbc:h2:tcp://localhost/~/hellparty